# docker-compose.yml
# -------------------------------------------------
# Orquesta la base de datos PostgreSQL y la API FastAPI
# en contenedores separados pero conectados entre sí.
# -------------------------------------------------

version: "3.9"

services:
  db:
    # Imagen oficial de PostgreSQL (versión estable 16)
    image: postgres:16
    
    # Nombre del contenedor para identificarlo fácilmente
    container_name: kopi_db
    
    # Reinicio automático salvo que lo detengas manualmente
    restart: unless-stopped

    # Variables de entorno inyectadas desde .env
    # Definir:
    #   POSTGRES_USER=usuario
    #   POSTGRES_PASSWORD=contraseña
    #   POSTGRES_DB=nombre_base
    #   POSTGRES_PORT=5432 (o el que definas en tu .env)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC

    # Exposición del puerto: se mapea el puerto local al del contenedor
    ports:
      - "${POSTGRES_PORT}:5432"

    # Volúmenes:
    # - pg_data: persistencia de datos
    # - ./scripts: carpeta local montada en docker-entrypoint-initdb.d
    #              PostgreSQL ejecutará automáticamente los .sql dentro de esta ruta
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d:ro

    # Healthcheck: asegura que el servicio esté "listo" antes de usarlo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s   # cada cuánto probar
      timeout: 3s    # tiempo máximo de espera
      retries: 10    # intentos antes de marcarlo como "unhealthy"

  api:
    # Construye la imagen de la API a partir del Dockerfile en la raíz
    build: .
    
    # Nombre del contenedor para identificarlo fácilmente
    container_name: kopi_api

    # Reinicio automático salvo que lo detengas manualmente
    restart: unless-stopped

    # La API depende de que la base de datos esté lista
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    # Variables de entorno que necesita la API
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    # Expone FastAPI en localhost:8000
    ports:
      - "8000:8000"

# Declaración de volúmenes
volumes:
  pg_data:  # persiste los datos en disco
